---
- name: "install Apache server"
  yum:
    name: httpd
    state: latest
  become: yes
- name: "install mysql server"
  yum:
    name: "{{packages}}"
    state: latest
  vars:
    packages:
    - mariadb
    - mariadb-server
- name: "install php"
  yum:
    name: "{{packages}}"
    state: latest
  vars:
    packages:
    - php
    - php-mysql
    - MySQL-python
- name: "Download WP"
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /tmp/wordpress.zip
- name: "Unarchive wordpress to specific destination"
  unarchive:
    src: /tmp/wordpress.zip
    dest: /var/www
    remote_src: yes
- name: "start mariadb"
  service:
    name: mariadb
    state: started
- name: "create a new database"
  mysql_db:
    name: "{{project_name}}"
    state: present
- name: Create database user
- name: "copy apache config"
  template:
    src: templates/blog.conf
    dest: /etc/httpd/conf.d/blog.conf
- name: "start httpd"
  service:
    name: httpd
    state: restarted
- name: "copy wp config"
  template:
    src: templates/wp-config.php
    dest: "{{wordpress_path}}/wp-config.php"